### ISSUE TITLE
symbol `vmovdqu32' redefined

### ISSUE THREAD

**Issue by kcmohanprasad** [01org/intel-ipsec-mb#11]
Hi,

I am trying to compile this code in Centos 7(3.10.0-514.10.2.el7.x86_64), getting this below error in .45 and .44 versions, is there any workaround for this issue
mb_mgr_hmac_sha_256_submit_avx512.asm:170: error: parser: instruction expected
mb_mgr_hmac_sha_256_submit_avx512.asm:171: error: symbol `vmovdqu32' redefined
mb_mgr_hmac_sha_256_submit_avx512.asm:171: error: parser: instruction expected
make: *** [obj/mb_mgr_hmac_sha_224_submit_avx512.o] Error 1

Thanks,
Mohan

**Comment by sgmonroy** [comment]
Hi,

What nasm version are you using?

Required tools:
- GNU make
- NASM version 2.12.02 (or newer)
- gcc (GCC) 4.8.3 (or newer)


Thanks,
Sergio

**Comment by isoke** [comment]
Thank you for the reply.

Upgraded nasm and got it fixed, thank you

**Comment by tkanteck** [comment]
thanks for the update and let me close this issue for now.
